language: csharp
sudo: required
dist: xenial
mono: latest
dotnet: 2.2.300
os:
  - linux
  - osx

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master

cache:
  bundler: true
  directories:
  - ./packages
  - /.dotnetcli
  - $HOME/.nuget/packages
  - $HOME/Library/Caches/Homebrew

before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

install:
  - git config --global core.autocrlf input
  - git submodule update --init --recursive

script:
  - dotnet build -c Release
  - dotnet test -c Release -f netcoreapp2.2 --no-build --no-restore --blame
  - mono $HOME/.nuget/packages/xunit.runner.console/*/tools/net452/xunit.console.exe ./test/Multiformats.Base.Tests/bin/Release/net461/Multiformats.Base.Tests.dll
